### ISSUE TITLE
Colorful Diffuse Intrinsic Image Decomposition in the Wild save images

### ISSUE THREAD

**Issue by ZiBrianQian** [compphoto/Intrinsic#11]
I'm using your script to run it on my own image 

```
from chrislib.data_util import load_image

from intrinsic.pipeline import load_models, run_pipeline

# load the models from the given paths
models = load_models('v2')

# load an image (np float array in [0-1])
image = load_image('/path/to/input/image')

# run the model on the image using R_0 resizing
results = run_pipeline(models, image)

albedo = results['hr_alb']
diffuse_shading = results['dif_shd']
residual = results['residual']
# + multiple other keys for different intermediate components
```

But how can I save the results and keep the original resolution? 
P.S.: Sorry for noobs question.

**Comment by CCareaga** [comment]
Hi,

There are multiple ways you can save the components depending on how you want to use them. For albedo, the values are already in the [0, 1] range, and can be easily saved as 8-bit PNGs. This will lose some accuracy due to quantization, but won't be too bad. The shading images on the other hand are high dynamic range quantities and should ideally be saved using a suitable format. For example they could be saved as EXR files (using imageio/opencv), or uncompressed as NPY files (`np.save()`). If you plan on recombining the components after saving, you will want to save them in a format that maintains their precision. If you are planning to use the components for something where the quality isn't as important and you need quick loading then you can save the components as PNGs. If you do this you may want to tonemap the shading (e.g. `x / (x + 1)` before saving to avoid clipping, then reverse this tonemapping once you load it. This of course can cause quantization artifacts for values that get compressed by the tonemapping.

For the resolution, do you mean use the original resolution of the input image? If so, you can just upscale the components to match the original size since there is a max resolution that we run our pipeline at. I can add a flag to the pipeline to automatically do this.

That's a lot of information, but hopefully it helps.

**Comment by ZiBrianQian** [comment]
Thank you a lot for your information!
