### ISSUE TITLE
Per-pixel white balancing

### ISSUE THREAD

**Issue by manuramesh96** [compphoto/Intrinsic#12]
Could you please provide code that performed the per-pixel white balancing on the images shown in your paper?
Or at least give the algo to do that using your shading array?
Thanks.

**Comment by CCareaga** [comment]
To compute the white balancing visualizations shown in the paper I use [this line](https://github.com/compphoto/Intrinsic/blob/9fb7d64ebe9205d9c0d8eb6284c47ff92cc66c67/intrinsic/pipeline.py#L326C5-L326C58):
 
```python
wb_img = (hr_alb * get_brightness(hr_shd)).clip(0, 1)
``` 

This image is returned by the pipeline as the `wb_img` key. The `get_brightness` function simply converts RGB to luminance, so I'm just desaturating the shading and re-applying it to the albedo. Note this can have weird side effects due to specularities and other lighting effects that get incorrectly represented in this shading component. A better approach might be to desaturate the diffuse shading, then reconstruct the image with the albedo and residual components. I haven't experimented with that yet though.
