### ISSUE TITLE
Multi-view consistent decomposition

### ISSUE THREAD

**Issue by charley077** [compphoto/Intrinsic#7]
Hi, thanks for the great work.
In my task, I aim to decomposite images from a multi-view image set. First I take images one-by-one as input to your model. Results of two views are presented as follows:
![WechatIMG18](https://github.com/user-attachments/assets/59d6439b-3572-4db5-907f-54effb62cd41)
![WechatIMG19](https://github.com/user-attachments/assets/49e2af01-753b-44ff-9360-b9c684ecda96)
It's obvious that the albedo images of the roof are not consistent.
Does this work provide multi-view consistency functionality? If not, could you please give me some advice to improve multi-view consistency when decompositing images into albedo and shading?
I sincerely look forward to your reply.

**Comment by CCareaga** [comment]
Our method isn't expected to be multi-view consistent, in general it's a pretty difficult problem to accomplish this. One easy thing is to make sure the arbitrary scale is matched between each decomposition. This won't fix all the inconsistencies though. Additionally, you would want to make sure the capture set up is consistent across views, in your example the apparent color of the roof appears darker in the top view and lighter in the top view, not sure if this is due to a difference in camera settings, or lighting in the scene. Another difficulty is handling view-dependent lighting effects (e.g. specularities). In the multi-view setup there may be ways of getting accurate geometry or correspondences that could help with consistency, but in its current form our pipeline isn't meant to address these issues.

**Comment by charley077** [comment]
Thanks for your reply! Close the issue.
