### ISSUE TITLE
Updated recoloring script

### ISSUE THREAD

**Issue by alorthius** [compphoto/Intrinsic#9]
Hi, thanks so much for the cool work! I am really interested in recoloring with your approach, however, since the recent changes in the model output, there is no more key 'inv_shading'.  Could you please show to reconstruct the final image given the intrinsic components? Or could you update recoloring.ipynb notebook to the latest changes? Thank you so much

**Comment by CCareaga** [comment]
Hi,

The `'inv_shading'` key has been changed to `'gry_shd'` to disambiguate it from the other shading layers in our new pipeline. The old recoloring script should still function correctly when using this new name. In order to load the old weights you would want to do:

```python
models = load_models('paper_weights')
````

This will load just the grayscale decomposition models used in our first paper. When you run the pipeline you can pass the argument `stage=1` to only run the grayscale pipeline. Alternatively, there is a function in `pipeline` that runs only the old pipeline called `run_gray_pipeline`. I haven't experimented with recoloring using our new pipeline but it should be able to handle many more illumination conditions. In our new pipeline the image is reconstructed as:

```python
result = run_pipeline(...)
image = result['hr_alb'] * result['hr_shd']
# or alternatively
image = result['hr_alb'] * result['dif_shd'] + result['residual']
```

This means you can edit the albedo, then reapply the shading layer in the same way as before. I'll work on updating the old recoloring notebook to account for this change.
